### ISSUE TITLE
Add styles for the new whiteboard feature 

### ISSUE THREAD

**Issue by griimick** [catppuccin/logseq#12]
This was requested in the official Logseq discord. A few new CSS variables and overrides were used in the feature which stand out of the theme.

**Comment by LateNightIceCream** [comment]
@griimick Have you worked on this already? Otherwise, I would give it a shot since I'd use it for my version as well :)

**Comment by LateNightIceCream** [comment]
So far so good. I tried to adhere to the default theme style. There are some tricky things to consider. E.g., the text and line colors share a variable. 

Also, for the shapes, like the rectangles in the screenshot, there are two options:
1. shade the text color and keep the shape fill color default (e.g. `--ctp-red`) - this is like the default theme
3. shade the fill and keep the text color default

I think option 1 it is actually a little hard to read but it is the same for the default theme. But I just noticed that the font size in the screenshots is a little small to judge that.

Another question is what exact color the shades should be. In the screenshots, I used a mix of `--ctp-colorX` with 60% `--ctp-base` for the fill or the text, respectively.

Lmk what you think!

Current:
![logseq-ctp-whiteboard-3](https://github.com/catppuccin/logseq/assets/13813609/8c53be57-589d-4c8b-a2cc-9e97dca1a382)

Option 1:
![logseq-ctp-whiteboard-1](https://github.com/catppuccin/logseq/assets/13813609/6eb3d88d-cadf-4f40-a40e-612bae5d0c1b)


Option 2:
![logseq-ctp-whiteboard-2](https://github.com/catppuccin/logseq/assets/13813609/a4389107-89b6-43dc-aac3-3684ee6d7b81)

**Comment by griimick** [comment]
I would prefer option 1 as it close to what default logseq theme. 

The readability can be improved by the users themselves as there's an option to choose a custom color. We might have to see how that works with this theme as well.

Can you open a PR for this as well? I would like to play around with it a bit.

**Comment by LateNightIceCream** [comment]
I agree! And I will open the PR tomorrow. I hope you won't mind the messiness ^^
