### ISSUE TITLE
Light theme and dark theme code block background color cannot be displayed correctly

### ISSUE THREAD

**Issue by zhouxinghong** [catppuccin/logseq#13]
Light theme and dark theme code block background color cannot be displayed correctly
v0.2.3
0.99

**Comment by griimick** [comment]
@zhouxinghong can you share a screenshot of the issue?

**Comment by LateNightIceCream** [comment]
I believe this this is about code blocks not having the codemirror css applied. In dark-mode it works but in light mode, the default theme appears (looks like solarized light). I have installed the plugin from the marketplace.

![logseq-ctp-code-block](https://github.com/catppuccin/logseq/assets/13813609/f0155b3a-26cd-4e58-848d-69284b169c53)

Btw, thank you for this great theme :). I am currently working on a Rosé Pine fork of this.

**Comment by LateNightIceCream** [comment]
opened a PR https://github.com/catppuccin/logseq/pull/14#issue-1894944788

**Comment by griimick** [comment]
fix merged. to be released in 0.2.4
