### ISSUE TITLE
Color customization for TODO,DOING,LATER,WAITING,DONE,CANCELED and Priorities 

### ISSUE THREAD

**Issue by kumaresh0** [catppuccin/logseq#16]
Hello 
Thanks for wonderful them, I really love it. 

Is it possible to add coloring for TODO,DOING,LATER,WAITING,DONE,CANCELED and Priorities  ? 
like for example todo -> blue, done -> green , waiting -> yellow  and customized priorities coloring 

<img width="118" alt="image" src="https://github.com/catppuccin/logseq/assets/117239791/31c22814-9021-40a5-ab00-1bd4aa64dbd3">

example used on dev theme
<img width="133" alt="image" src="https://github.com/catppuccin/logseq/assets/117239791/e012a2e8-9d65-410e-8584-5d9430425085">

Coloring for priority 
example used on dev theme
<img width="109" alt="image" src="https://github.com/catppuccin/logseq/assets/117239791/e9b9c35b-e828-4983-b782-4f83153a7558">

<img width="224" alt="image" src="https://github.com/catppuccin/logseq/assets/117239791/eb68603e-f39e-43c6-852c-914ebbbf62ae">

**Comment by griimick** [comment]
Yes, it can be done.

**Comment by griimick** [comment]
This what it looks like now,
<p float="left">
<img src="https://github.com/catppuccin/logseq/assets/10350864/88c321e6-4b37-4009-81d5-9782a1e37901" />
<img src="https://github.com/catppuccin/logseq/assets/10350864/fa6b8662-899c-49eb-9e1c-7cb35b829a1b" />
</p>
Customisation will be added in future along with many other overrides under settings. For now you can override the variables using custom css.
