### ISSUE TITLE
Regression issues from v0.5

### ISSUE THREAD

**Issue by griimick** [catppuccin/logseq#28]
Issues reported over Logseq discord and DM,
- [x] button icon color not visible (Recent and Favorite item options)
- [x] Theme selection item on hover picks default theme color
- [x] theme breaks completely with v0.10.6 which does not have the option to cancel accent selection (reported by @Chais)
- [x] whiteboard tooltips and status bar colors (reported by @jh-devv)

**Comment by Chais** [comment]
I'd go so far as to say the theme is barely applied at all
This is the default theme:  
![Screenshot from 24-03-05_16:22:27](https://github.com/catppuccin/logseq/assets/1783098/f8d6e69f-85cd-432d-a54d-a487ba12bafe)

And this is with Catppuccin-Mocha applied:  
![Screenshot from 24-03-05_16:22:35](https://github.com/catppuccin/logseq/assets/1783098/542253e7-db06-4e47-8436-7df1aff2392e)

As you see there's a slight gradient in the background, but that's about it. Also I noticed the config editor is nearly unusable, as it doesn't display a cursor nor highlight the current line or selected text, making navigation and editing rather challenging.

**Comment by griimick** [comment]
@Chais Thanks for reporting. Can you share what version of Logseq and Catppuccin theme are you using?

If you are using the latest Logseq v0.10.7, please make sure to cancel the accent selection as this theme currently does not support any of the accents (not even the default Logseq accent). 
<img width="544" alt="Screenshot 2024-03-05 at 9 01 31 PM" src="https://github.com/catppuccin/logseq/assets/10350864/a55b1840-fc03-4818-bdb1-595b155ce443">

**Comment by Chais** [comment]
I did not. Running on NixOs 23.11, so I had 0.10.6, which didn't offer that option. Pulling 0.10.7 from unstable fixed my issues. Sorry for the noise.

**Comment by griimick** [comment]
> I did not. Running on NixOs 23.11, so I had 0.10.6, which didn't offer that option. Pulling 0.10.7 from unstable fixed my issues. Sorry for the noise.

No worries! Thanks again for reporting, I will test with 0.10.6 and include a fix if it has broken for an older version which shouldn't have been in the first place!

**Comment by jh-devv** [comment]
@Chais @griimick 
Is this issue related? After updating to the newer version (at least the theme loads now), the whiteboard looks kinda bad?
![image](https://github.com/catppuccin/logseq/assets/122896463/92a0a15d-fc63-452a-b2d7-e87262efedf1)

**Comment by jh-devv** [comment]
This seems to happen on other themes also, weird?

**Comment by Chais** [comment]
You'll have to be more specific.  
New version of the theme?  
Tested on which version of logseq?

**Comment by jh-devv** [comment]
> You'll have to be more specific. New version of the theme? Tested on which version of Logseq?

Oh sorry,

Logseq version: [0.10.7](https://github.com/logseq/logseq/commit/1ff9f7a) 
Theme version: v0.5

**Comment by Chais** [comment]
I'm not sure what exactly you're referring to. But I never used whiteboards all that much, so I'm not very familiar with their look.  
![Screenshot from 24-03-05_19:44:11](https://github.com/catppuccin/logseq/assets/1783098/47659968-1a2c-4c40-8272-e8f44db85752)

**Comment by griimick** [comment]
> Logseq version: [0.10.7](https://github.com/logseq/logseq/commit/1ff9f7a) Theme version: v0.5

@jh-devv Thanks for the report!

I can repro this. As Logseq is undergoing its design system changes, lots of element styles are breaking and will keep breaking in future releases. I have added this to the list above for the next release.

<img width="702" alt="image" src="https://github.com/catppuccin/logseq/assets/10350864/a608c82a-6510-488c-a07e-65baa018f6ff">

<img width="702" alt="image" src="https://github.com/catppuccin/logseq/assets/10350864/8f52b5f7-a7b1-4320-b6cb-673022bc26ee">

**Comment by jh-devv** [comment]
> > Logseq version: [0.10.7](https://github.com/logseq/logseq/commit/1ff9f7a) Theme version: v0.5
> 
> @jh-devv Thanks for the report!
> 
> I can repro this. As Logseq is undergoing its design system changes, lots of element styles are breaking and will keep breaking in future releases. I have added this to the list above for the next release.
> <img alt="image" width="702" src="https://private-user-images.githubusercontent.com/10350864/310242693-a608c82a-6510-488c-a07e-65baa018f6ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NjQ2OTQsIm5iZiI6MTcwOTY2NDM5NCwicGF0aCI6Ii8xMDM1MDg2NC8zMTAyNDI2OTMtYTYwOGM4MmEtNjUxMC00ODhjLWEwN2UtNjViYWEwMThmNmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE4NDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNzU2ODc3MGE1MzNjMWQyYTdhZTU1NWQ2YzE4YzU4ODM3YjliNTNiYjhmNWE0YTg2NWZhNzc3YmIwYzUxYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bbbzksYVOTm1h_NKwCXTPCQuNZjSF77TpQ1zs98CJYk"> <img alt="image" width="702" src="https://private-user-images.githubusercontent.com/10350864/310242394-8f52b5f7-a7b1-4320-b6cb-673022bc26ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NjQ2OTQsIm5iZiI6MTcwOTY2NDM5NCwicGF0aCI6Ii8xMDM1MDg2NC8zMTAyNDIzOTQtOGY1MmI1ZjctYTdiMS00MzIwLWI2Y2ItNjczMDIyYmMyNmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE4NDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MzA2ZTUyYmMzZjZlMTFlMmIxYjAzNzQxZWZlN2EwZmM4NjgyMDk3NDc5NGRlN2U0ZjI2MjM0N2FjNTkxOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lEucIAXoEd-3C-QQhVUQ5ei7Ee2v7GHIJIp8MzPMCc4">

Thanks! :)

**Comment by rich-williamson** [comment]
+1 to this, I'm having the same issue since updating to 0.5. The theme is basically not working at all on any flavour. Logse 0.10.6 on Ubuntu if that helps.
