### ISSUE TITLE
switching from light to dark theme using `t t` made undoable change to the accent of bold + italics accent ( using `***text***`) and the accent of header tools.

### ISSUE THREAD

**Issue by SumirSeth** [catppuccin/logseq#34]
I was previewing themes using the `t t` shortcut but it caused colors to swap, mainly the accent color of the bold+underline texts and the tool section in the headerbar.
I have tried reinstalling the theme and refreshing logseq but nothing works. Please help!
![image](https://github.com/catppuccin/logseq/assets/79976481/a0567cc9-794e-44ca-9a9e-673d804bfd2b)

**Comment by griimick** [comment]
I checked the latest version of the theme. It is the same as what you have in the screenshot. It is possible that you were using an older version of the theme and it got updated or it was somehow misconfigured.

- Was bold+italics text getting accent color by default?
- Were the tool icons in the tool section of the header behaving the same as the other icons (forward, backward, show/hide sidebar) i.e. without accent color?

**Comment by SumirSeth** [comment]
- yes, bold+italics was getting that accent by default and i did not change anything to specially add colors to it.
- there is no behavioural change of the header tools with or without acccent.

It could be that it was somehow misconfigured previously and changing the theme somehow "refreshed" it, but I feel like it does not make sense to have accent in the header icons when the home icon, sidebar icon and forward/backward arrows dont have an accent to them. It just adds inconsistency in my opinion.

While I also think that adding accent to the bold+italic text would be a great addition but that is ofc up to personal preferences of the devs.

**Comment by griimick** [comment]
Thank you! I agree with both the points. Will add them as action items.
- [ ] Fix styles of plugin tools in headers to match other items
- [ ] Add accent color (and fallback color) for bold+italic text as italic only also has one.

**Comment by SumirSeth** [comment]
thank you so much!!
