### ISSUE TITLE
Selected text too hard to read

### ISSUE THREAD

**Issue by widogg** [catppuccin/logseq#39]
Hello!

I'm finding that selected text is too hard to read, I don't know if the text color here is the correct or not 
![image](https://github.com/catppuccin/logseq/assets/72229882/58898bcf-e2b5-4f83-b078-92068c40cd20)

I'm using LogSeq 0.10.6 with Catppuccin theme 0.6.1 (dark theme + Catpuccin Macchiato selected). I don't have any accent selected and I'm using `full palette`. I don't think I have modified any css or config file. Not intentionally.

I also noticed PR #21 which... seems related?

**Comment by griimick** [comment]
Thank you for the report. I am surprised that I broke this again. I will push out a fix soon

**Comment by widogg** [comment]
I'm not sure _when_ it broke. I think it was like this on 0.6.0 (I didn't reported it). 

Also, I just updated LogSeq to 10.8 and it still behaves the same

**Comment by griimick** [comment]
Pushed a fix in v0.6.2 of theme

**Comment by widogg** [comment]
definetly improved. Thanks ❤️ !
![image](https://github.com/catppuccin/logseq/assets/72229882/77dd742e-ac78-471a-9f3b-fa53040166a2)
