### ISSUE TITLE
Editor colors are off since last update

### ISSUE THREAD

**Issue by Erwyn** [catppuccin/logseq#42]
Hello,

I don't know if it's something that broke in the last update, but since it the editor colors at least in the light themes are not conform anymore. I'm back to something that very much looks like the standard logseq light theme.

Anybody experiencing the same thing ?

**Comment by Erwyn** [comment]
For the record, I tried to disable all plugins and comment out my own CSS tweaks to be sure this was not coming from this. It did not change anything.

**Comment by griimick** [comment]
Thanks for the report. Please share,

1. logseq version
2. theme version
3. screenshot of the issue if possible

While at it, please also make sure that the following options are set,
1. Catppuccin theme variant under Themes
2. "Light"/"Dark" theme under Settings > General > Theme
3. "Cancel accent color" under Settings > General > Accent Color

**Comment by Erwyn** [comment]
Hello !

Thanks for your answer.

> Thanks for the report. Please share,
> 
>     1. logseq version
0.10.6
> 
>     2. theme version
0.6.2
> 
>     3. screenshot of the issue if possible

![image](https://github.com/catppuccin/logseq/assets/206743/945f3600-7b0b-4618-a8d1-d9911e0e3fda)

> 
> 
> While at it, please also make sure that the following options are set,
> 
>     1. Catppuccin theme variant under Themes
![image](https://github.com/catppuccin/logseq/assets/206743/1c78a6f0-3ddf-490a-a85d-d3bbec777824)
> 
>     2. "Light"/"Dark" theme under Settings > General > Theme
![image](https://github.com/catppuccin/logseq/assets/206743/d854e5e2-06a4-40a7-82ff-6c05672fccc2)
> 
>     3. "Cancel accent color" under Settings > General > Accent Color
see previous screenshot

**Comment by griimick** [comment]
Please upgrade Logseq to at least v0.10.7. 

Logseq introduced its new design system in v0.10.6 which broke support for nearly all custom themes. After upgrading you should see these two options under accent color, we support both of those.

<img width="881" alt="Screenshot 2024-04-26 at 10 38 45 PM" src="https://github.com/catppuccin/logseq/assets/10350864/39ee8c94-f58d-4d8f-a2d3-c493dce34427">

**Comment by Erwyn** [comment]
ok, trying that

**Comment by Erwyn** [comment]
Updated to 0.10.8 (that's what is the unstable of Nixos). It's indeed working now. Thank you very much
