### ISSUE TITLE
theme not applying

### ISSUE THREAD

**Issue by theotheroracle** [catppuccin/logseq#57]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

i tried to download the theme from the plugin repo, and also applied it via custom css but neither worked, and it remains the default theme, but i tested another theme and that worked, so i'm not sure if i'm doing something wrong or if the theme is broken ?

logseq: 0.10.9  c67b8b5

### Attach screenshots.

![image](https://github.com/user-attachments/assets/65ad17bf-cef2-45b6-8742-27fee93c21bd)
![image](https://github.com/user-attachments/assets/db1ca9c1-0cdb-4bff-aa51-6b7d5bfa5497)

### What Logseq version do you see the issue on?

0.10.9 

### What theme version do you see the issue on?

0.6.3

### Any additional comments?

i'm running on nixos if that's makes a difference

**Comment by griimick** [comment]
Hey @theotheroracle, thanks for the report. Yes, the external CSS theme setup is broken but installing as a plugin should have worked. 

Can you share screenshot your Logseq setting screen especially the ones under general. Example,
<img width="832" alt="image" src="https://github.com/user-attachments/assets/c24d8156-ee0c-4a75-b176-cf01983c0397">

**Comment by griimick** [comment]
Ah! Please try selecting one of the two starting accent options. We don't support the official accent colors and don't plan to. I will update the README to better warn users about this.

![image](https://github.com/user-attachments/assets/ff67e924-045d-4a81-ad29-ff5555c43464)

For setting accent colors in catppuccin theme, you can use the custom settings option as described [here](https://github.com/catppuccin/logseq?tab=readme-ov-file#switching-accent-color)

**Comment by theotheroracle** [comment]
oh thank you so much !!!
