### ISSUE TITLE
Preserving Built CSS Files

### ISSUE THREAD

**Issue by shaonianche** [catppuccin/logseq#6]
The Logseq project supports importing online CSS files, is it possible to preserve the built CSS files for future imports?

https://github.com/logseq/logseq/blob/master/templates/config.edn#L72

**Comment by griimick** [comment]
Yes, it should be possible. I will include the built CSS files in the next release assets. Also, heads up the theme is now available in the Logseq marketplace.

**Comment by astronaute-nope** [comment]
On the home page you have : 

- Logseq Plugin Marketplace (Soon TBD)

Should the () be removed ?

**Comment by griimick** [comment]
> On the home page you have :
> 
> * Logseq Plugin Marketplace (Soon TBD)
> 
> Should the () be removed ?

Updated README. Thanks for pointing that out.

**Comment by griimick** [comment]
@shaonianche Just made a new release and now all built stylesheets are served by GitHub pages. You can add one of the following in your config in case you prefer that way over downloading the theme from Logseq Marketplace.
```edn
:custom-css-url "@import url('https://logseq.catppuccin.com/ctp-latte.css');"
:custom-css-url "@import url('https://logseq.catppuccin.com/ctp-frappe.css');"
:custom-css-url "@import url('https://logseq.catppuccin.com/ctp-macchiato.css');"
:custom-css-url "@import url('https://logseq.catppuccin.com/ctp-mocha.css');"
```
Closing the issue for now.

**Comment by vuongtrunghieu** [comment]
> @shaonianche Just made a new release and now all built stylesheets are served by GitHub pages. You can add one of the following in your config in case you prefer that way over downloading the theme from Logseq Marketplace.
> 
> ```clojure
> :custom-css-url "@import url('https://logseq.catppuccin.com/ctp-latte.css');"
> :custom-css-url "@import url('https://logseq.catppuccin.com/ctp-frappe.css');"
> :custom-css-url "@import url('https://logseq.catppuccin.com/ctp-macchiato.css');"
> :custom-css-url "@import url('https://logseq.catppuccin.com/ctp-mocha.css');"
> ```
> 
> Closing the issue for now.

I tried to set theme on mobile, but these resource URLs are not accessible.

**Comment by griimick** [comment]
@vuongtrunghieu Thanks for mentioning this. I broke it with my workflow. I should be working now.
