### ISSUE TITLE
Can't select items from the drop-dwon list

### ISSUE THREAD

**Issue by CharlesChiuGit** [catppuccin/logseq#8]
In original logseq theme, we can select items from the drop-down list with up/down arrow keys.
However, it not doable with catppuccin theme. Similar behavior is only available via mouse.

![圖片](https://user-images.githubusercontent.com/32497323/221407086-10596828-23e5-4afd-963e-51ba002f7602.png)
For example, the `Zotero` item is only highlighted when my mouse is on it.

**Comment by griimick** [comment]
Thanks for reporting this. Let me debug this in by the coming weekend.

**Comment by CharlesChiuGit** [comment]
v0.2.2 haven't release?

**Comment by griimick** [comment]
Github Actions service is down right now. The release is in queue. It should be available once the service is back online.

**Comment by CharlesChiuGit** [comment]
Aha, thanks for clarifying that.

**Comment by CharlesChiuGit** [comment]
That's a bit weird. Mine github actions looks fine.
<br/>

![圖片](https://user-images.githubusercontent.com/32497323/222615344-6d2b50ef-317a-49e5-a90a-4de6b16a2b67.png)

**Comment by griimick** [comment]
Yes, the services are back up now.  I'll rerun the release jobs.

**Comment by CharlesChiuGit** [comment]
Can confirm it's fixed, tks!
